In [57]:
with open('./data/ks_19_0', 'r') as input_data_file:
    input_data = input_data_file.read()

In [10]:
from collections import namedtuple
import numpy as np
Item = namedtuple("Item", ['index', 'value', 'weight'])

lines = input_data.split('\n')


firstLine = lines[0].split()
item_count = int(firstLine[0])
capacity = int(firstLine[1])

items = []

for i in range(1, item_count+1):
    line = lines[i]
    parts = line.split()
    items.append([i-1, int(parts[0]), int(parts[1])])

In [55]:
capacity

31181

In [58]:
items_array = np.array(items)
items_array

array([[    0,  1945,  4990],
       [    1,   321,  1142],
       [    2,  2945,  7390],
       [    3,  4136, 10372],
       [    4,  1107,  3114],
       [    5,  1022,  2744],
       [    6,  1101,  3102],
       [    7,  2890,  7280],
       [    8,   962,  2624],
       [    9,  1060,  3020],
       [   10,   805,  2310],
       [   11,   689,  2078],
       [   12,  1513,  3926],
       [   13,  3878,  9656],
       [   14, 13504, 32708],
       [   15,  1865,  4830],
       [   16,   667,  2034],
       [   17,  1833,  4766],
       [   18, 16553, 40006]])

In [59]:
# smaller item first
items_array_sorted = items_array[items_array[:,2].argsort()]


In [61]:
value = 0
weight = 0
taken = [0] * items_array_sorted.shape[0]

for i in range(0, items_array_sorted.shape[0]):
    if weight + items_array_sorted[:, 2][i]<= capacity:
        value += items_array_sorted[:, 1][i]
        weight += items_array_sorted[:, 2][i]
        taken[items_array_sorted[:, 0][i]] = 1
        
value

11080

In [64]:
# most valueable item first
items_array_sorted = items_array[items_array[:,1].argsort()[::-1]]


In [66]:
value = 0
weight = 0
taken = [0] * items_array_sorted.shape[0]
for i in range(0, items_array_sorted.shape[0]):
    if weight + items_array_sorted[:, 2][i] <= capacity:
        value += items_array_sorted[:, 1][i]
        weight += items_array_sorted[:, 2][i]
        taken[items_array_sorted[:, 0][i]] = 1

In [67]:
value

12066

In [78]:
items_array

array([[    0,  1945,  4990],
       [    1,   321,  1142],
       [    2,  2945,  7390],
       [    3,  4136, 10372],
       [    4,  1107,  3114],
       [    5,  1022,  2744],
       [    6,  1101,  3102],
       [    7,  2890,  7280],
       [    8,   962,  2624],
       [    9,  1060,  3020],
       [   10,   805,  2310],
       [   11,   689,  2078],
       [   12,  1513,  3926],
       [   13,  3878,  9656],
       [   14, 13504, 32708],
       [   15,  1865,  4830],
       [   16,   667,  2034],
       [   17,  1833,  4766],
       [   18, 16553, 40006]])

array([0.38977956, 0.28108581, 0.3985115 , 0.39876591, 0.35549133,
       0.37244898, 0.3549323 , 0.39697802, 0.36661585, 0.35099338,
       0.34848485, 0.33156882, 0.38537952, 0.40161558, 0.41286535,
       0.38612836, 0.32792527, 0.38459924, 0.41376294])

In [95]:
np.set_printoptions(suppress=True)
value_density = np.append(items_array,(items_array[:,1]/items_array[:,2]).reshape(-1,1), axis=1)

In [99]:
# higher value density first
items_array_sorted = value_density[value_density[:,3].argsort()[::-1]]


value = 0
weight = 0
taken = [0] * items_array_sorted.shape[0]
for i in range(0, items_array_sorted.shape[0]):
    if weight + items_array_sorted[:, 2][i] <= capacity:
        value += items_array_sorted[:, 1][i]
        weight += items_array_sorted[:, 2][i]
        taken[int(items_array_sorted[:, 0][i])] = 1
        
value

11981.0

In [103]:
import requests
from bs4 import    BeautifulSoup

In [118]:
url = 'https://www.benq.com/en-au/lamps/computer-desklamp/screenbar-plus.html'

import urllib.request
contents = urllib.request.urlopen(url)

In [122]:
contents